#-- vim:sw=2:et
#++
#
# :title: BruceFactPlugin
#
# Author:: David Koppel <admin@administrhater.com>
# Copyright:: (C) 2013 David Koppel
# License:: DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE http://www.wtfpl.net/txt/copying/
#

class BruceFactPlugin < Plugin
  # Facts from http://www.chmil.org/bruce-facts-all.txt 
@@facts = [
"Bruce Schneier got a perfect score on his comp-sci degree. Just by writing Bruce Schneier for every answer.",
"Bruce Schneier memorizes his one time pads",
"Bruce Schneier can reverse any one-way cryptographic hash, just by staring it in the eye",
"Bruce Schneier once found the inverse of a trapdoor function counting only on the fingers of one hand",
"The output of Bruce Schneier's pseudorandom generator follows no describable pattern and cannot be compressed.",
"Bruce Schneier mounts chosen-ciphertext attacks without choosing the ciphertext",
"Beyond computational complexity, there is Schneiertational complexity",
"Bruce Schneier can straighten out an elliptic curve with nothing but his teeth",
"Bruce Schneier makes abstract algebra look like elementary algebra.",
"Whitfield Diffie and Martin Hellman use only their surnames out of fear of Bruce Schneier",
"Bruce Schneier can conduct secure multiparty computation... on his own",
"Bruce Schneier mounts side-channel attacks through the front channel",
"Bruce Schneier's discrete logarithms are uncountable and continuous",
"Bruce Schneier always inhabits the soundness of error margin of your zero-knowledge crypto protocol",
"When Bruce Schneier pre-computes S-box tables, he does it dynamically from the key... over breakfast.",
"Bruce Schneier can determine the exact location and velocity of any particle that's being used by quantum cryptography.",
"Quantum cryptography exchanged the Heisenberg Uncertainty Principle for the Schneier Dead Moral Certainty Principle when Bruce Schneier came to town.",
"Bruce Schneier knows Alice and Bob's shared secret.",
"Bruce Schneier eats 0s and 1s for breakfast. And snacks on pi.",
"Bruce Schneier assembled assembly...with his bare hands!",
"Bruce Schneier is computationally infeasible.",
"A mystery wrapped in an Enigma is no more puzzling to Bruce Schneier than a mystery wrapped in ROT-13.",
"Bruce Schneier doesn't even trust Trent. Trent has to trust Bruce Schneier.",
"Bruce Schneier once found three distinct natural number divisors of a prime number.",
"As Bruce Schneier says there is no Oscar for security theatre.",
"Bruce Schneier's secure handshake is so strong, you won't be able to exchange keys with anyone else for days.",
"Most people use passwords. Some people use passphrases. Bruce Schneier uses an epic passpoem, detailing the life and works of seven mythical Norse heroes.",
"Bruce Schneier's online purchases are so secure, his shopping cart is an M-1 tank.",
"Bruce Schneier doesn't need steganography to hide data in innocent-looking files. He just pounds it in with his fist.",
"Bruce Schneier can solve NP-Complete problems in NlogN time.",
"Bruce Schneier's tears can burn holes through an OpenBSD firewall.  Lucky for us, Bruce Schneier never cries.",
"Bruce Schneier writes his books and essays by generating random alphanumeric text of an appropriate length and then decrypting it.",
"If you use the digits of Pi to generate a visual image, it draws a picture of Bruce Schneier.",
"The universe was created to serve as Bruce Schneier's crib text.",
"SSL is invulnerable to man-in-the-middle attacks. Unless that man is Bruce Schneier.",
"When he was three, Bruce Schneier built an Enigma machine out of Legos.",
"Bruce Schneier fully discloses his own vulnerabilities: none.",
"Bruce Schneier knows your private key.",
"Bruce Schneier's Twofish algorithm has 16 rounds, but he always gets a knockout in the first.",
"The nuclear launch codes held by the President of the United States are secured by an unbreakable system: a plain brown envelope with a picture of Bruce Schneier on the flap.",
"Ron Rivest wears Bruce Schneier pajamas.",
"Bruce Schneier was only allowed to view the Kryptos sculpture at Langley for 1 second, in order not to spoil the fun other cryptographers. It was 0.9 seconds too much.",
"Bruce Schneier doesn't have a chin under his beard -- just more ciphertext.",
"If at first you don't succeed at breaking a cipher, you're not Bruce Schneier.",
"In a fight between Ron Rivest and Adi Shamir, the winner would be Bruce Schneier.",
"There is no chin behind Bruce Schneier's beard. There is only another pseudorandom number generator and he's gonna use it to encrypt your face.",
"When Bruce Schneier does modulo arithmetic, there are no remainders. Ever.",
"Bruce Schneier made Bell-LaPadula do a brutal doodle.",
"Bruce Schneier once broke AES using nothing but six feet of rusty barbed wire, a toothpick, and the front axle from a 1962 Ford Falcon.",
"Every time Bruce Schneier smiles, an amateur cryptographer dies.",
"Mr. T pities the fool. Bruce Schneier just pities his data.",
"Bruce Schneier can change most random distributions. With his fists.",
"Sweeping NSA reforms will soon require all employees to grow a Bruce Schneier beard.",
"As initialization vectors, 'Bruce Schneier' and 'Chuck Norris' are interchangeable.",
"When Bruce Schneier uses double ROT13 encryption, the ciphertext is totally unbreakable.",
"The final Beale Cipher, written 175 years ago, detailing the rightful owners of a cache of gold, has just two words in its plaintext: Bruce Schneier.",
"Bruce Schneier sneers and solves Gödel's incompleteness theorems.",
"Humboldt squids have sensors capable of detecting clothing worn by Bruce Schneier at 800 yards - to trigger their flight response.",
"Every time Bruce Schneier writes a fully general halt-checker, God kills a passenger pigeon.  This is why passenger pigeons are extinct.",
"Bruce Schneier writes his personal journal in Linear A.",
"If Bruce Schneier rot-13s a plaintext, it cannot be broken by applying rot-13 again.",
"Albert Einstein wears Bruce Schneier pajamas",
"Bruce Schneier was born with the Phaistos Disk in his fist.",
"P = NP in Bruce Schneier's very presence.",
"There are no finite state machines. There are only a series of states that Bruce Schneier allows to exist.",
"When the Zodiac Killer heard that Bruce Schneier was going to decrypt his messages, he turned himself in.",
"The only reason the Etruscan incriptions haven't been decyphered is because Bruce Schneier hasn't been bored enough to take a look.",
"Bruce Schneier PGP signs his grocery lists so that he can detect if someone has tampered with his milk.",
"Bruce Schneier is the ideal man. Alice loves him; Bob fears him; Charlie wants to be him.",
"Bruce Schneier cuts meat in prime number lengths.",
"Bruce Schneier once decrypted a box of AlphaBits.",
"Bruce Schneier is Knuth's homeboy.",
"Bruce Schneier taught Chuck Norris how to divide by zero as they stood silent in an elevator.",
"Bruce Schneier is the seed for your random number generator.",
"Bruce Schneier's mail server only sends him the emails' hashes, just to make things a little more interesting for him.",
"Bruce Schneier obtained his legendary cryptoanalytic skills through a deal with the devil. He then proceeded to encrypt the devil's personal information and barter the plaintext for his soul.",
"Bruce Schneier can slam a logic gate. ",
"When God needs a new secure certificate, he uses Bruce Schneier as the signing authority.",
"For Bruce Schneier, quanta only have one state : afraid.",
"Bruce Schneier is not only the man-in-the-middle, he's at both ends and has wiretaps on Alice, Bob, Carol and Dave.",
"BRUCE SCHNEIER understands that all finite sets are countable , but not all countable sets are finite.",
"Can Bruce Schneier cypher something that not even He can decypher? Of course he can, and he can decypher it too.",
"Bruce Schneier beard has the bigger prime number of hairs",
"Bruce Schneier is the reason that 57 isn't prime.",
"Bruce Schneier once gave a roundhouse kick to the Internet. The backbone collapsed.",
"Bruce Schneier does not leak information on the EM spectrum: he emits the theme to The Good, The Bad, and The Ugly.",
"Bruce Schneier once killed a man using only linear cryptanalysis.",
"Bruce Schneier factors integers in constant time.",
"Bruce Schneier knows where Grigori Perelman is.",
"There is no such thing as security by obscurity, but only because there is no such thing as obscurity.  Bruce Schneier can always see you.",
"Bruce Schneier can decrypt your PKI message with the public key.",
"The birthday referred to in the 'Birthday Attack' is Bruce Schneier's.",
"Bruce Schneier reads RFID cards with the knuckles of his clenched fist.",
"The last person to attempt to steal Bruce Schneier's identity lost his memory and has never recovered.",
"There are no such thing as Carmichael numbers, only primes that Bruce Schneier has beaten factors into. ",
"Bruce Schneier doesn't believe in terrorist profiling because he already knows who all the terrorists are.",
"Alice and Bob got Eve pregnant together; the result was Bruce Schneier.",
"There is no Information Theory. Just data that Bruce Schneier allows to be quantified and transmitted on a channel.",
"Bruce Schneier and Lance Armstrong once had a contest to see who had more testicles.  Bruce was forced to forfeit when no one could decrypt his scrotum.",
"Bruce Schneier's fists violate the anti-circumvention clause of the Digital Millennium Copyright Act.",
"When Bruce Schneier decrypts the Da Vinci Code, the ending doesn't suck",
"There is an otherwise featureless big black computer in Ft. Meade that has a single dial with three settings: Off, Standby, and Schneier.",
"Bruce Schneier doesn't even know the meaning of the word ciphertext, because to him, everything is plaintext.",
"Bruce Schneier knows you are reading this.",
"Bruce Schneier's private key is so strong that he doesn't even hide it -- if you saw it, you'd die before you could use it.",
"Bruce Schneier doesn't keep secrets -- they keep themselves out of fear.",
"Bruce Schneier whistles white noise.",
"Bruce Schneier can losslessly compress random data by 50%, with his fists.",
"When Bruce Schneier divides the circumference of a circle by the radius, the answer is rational.",
"Anyone who makes love to Bruce Schneier discovers a 0-day flaw in a crypto protocol the next day.",
"Bruce Schneier can log into any computer just by staring down the prompt.",
"The spacing between Bruce Schneiers ribs forms an Optimal Golomb Ruler.",
"If Bruce Schneier was a bacteria, he'd be a virulent form of Cryptosporidia.",
"Bruce Schneier doesn't use a keylogger.  He's standing right behind you.",
"Bruce found a secure way to reuse a one-time pad.",
"Bruce Schneier's DNA is a secure platform and cannot be cloned.",
"Bruce Schneier's skin has no pores. Pores are vulnerabilities.",
"Bruce Schneier is not balding, you just can't see the encrypted portions of his hair.",
"Though a superhero, Bruce Schneier disdanes the use of a mask or secret identity as 'security through obscurity'.",
"Adi Shamir stopped working on factoring once he learnt that Bruce Schneier can solve sparse linear systems by shaking them Etch-a-sketch style.",
"An autographed picture of Bruce Schneier is all you need to securely wipe any hard-drive.",
"On Bruce Schneier's birthday, a person standing at the very center of Stonehenge casts a shadow in the shape of Bruce Schneier's PGP public key fingerprint.",
"The phonograph record included on the Voyager probe contains a hidden watermark inserted by Bruce Schneier.",
"Bruce Schneier's name appeared in EBCDIC in the output of /dev/random every time there was a full moon.  Even after they changed the RNG algorithm.",
"Only one security god has a surname with three adjacent vowels.",
"Bruce Schneier doesn't need facts. With one roundhouse-kick he can generate a formal proof for whatever he needs.",
"Bruce Schneier only smiles when he finds an unbreakable cryptosystem. Of course, Bruce Schneier never smiles.",
"Bruce Schneier tampers with tamperproof hardware.",
"The Dining Cryptographers always wait until Bruce Schneier has been served.",
"Bruce Schneier tapdances in Morse Code.",
"Bruce Schneier gets the jokes in the Voynich MS.",
"Bruce Schneier knows the state of schroedinger's cat",
"Crytanalysis doesn't break cryptosystems. Bruce Schneier breaks cryptosystems.",
"Bruce Schneier has a tattoo of the value of the Ramsey number R(5,5).",
"If you manage to steal Bruce Schneier's identity, you become the new Bruce Schneier.",
"Bruce Schneier doesn't need to hide data with steganography - data hides from Bruce Schneier",
"Bruce Schneier doesn't need full vulnerability disclosure because he already knows.",
"Bruce Schneier once proved the infinitude of twin primes -- by enumeration.",
"Bruce Schneier knows the last digit of pi. He won't say it because it's considered a matter of national security.",
"Vs lbh nfxrq Oehpr Fpuarvre gb qrpelcg guvf, ur'q pehfu lbhe fxhyy jvgu uvf ynhtu.",
"Bruce Schneier has found SHA-512 preimages of all these facts.",
"Nuclear physicists at Fermilab were amazed to find that Bruce Schneier's internal clock is more reliable than the vibrations of a Cs-133 atom.",
"Bruce Schneier decided the color of the blue box",
"Bruce Schneier's earliest childhood memory is encrypted.",
"Bruce Schneier can determine if a program terminates just by looking at it. And then the program terminates itself.",
"Bruce Schneier makes a mean Bearnaise sauce. But you need a password to access it. ",
"Attempting to decrypt Bruce Schneier's cyphertext causes extreme time dilation",
"Bruce Schneier's social security number is a Sophie Germain prime number having a reciprocal generating an infinite stream of pseudorandom numbers.",
"The set of Bruce Schneier's weaknesses is a mathematical constant. It is represented by the symbol ∅.",
"Bruce Schneier expects the Spanish Inquisition.",
"For Bruce Schneier, SHA-1 is merely a compression algorithm.",
"Bruce Schneier's wedding invitations included instructions for participating in a cryptographically secure RSVP protocol.",
"If we built a Dyson sphere around Bruce Schneier and captured all of his energy for 2 months, without any loss, we could power an ideal computer running at 3.2 degrees K to count up to 2^256. This strongly implies that not only can Bruce Schneier brute-force attack 256-bit keys, but that he is built of something other than matter and occupies something other than space. ",
"Bruce Schneier can cook a perfect prime rib",
"Radia Perlman may be the mother of the Internet, but Bruce Schnier is the mutha of the Internet.",
"Bruce Schneier can smell weak keys.",
"Bruce Schneier's abs are NP-hard.",
"Santa Clause doesn't know if Bruce Schneier has been good or bad",
"Bruce force: recovering a password or key by typing it in correctly on the first try.",
"Bruce Schneier can see SHA-256 collisions by holding a hash up to a mirror and crossing his eyes.",
"Bruce Schneier's p is irrational, and his q is imaginary.",
"When Bruce Schneier observes a quantum particle, it remains in the same state until he has finished observing it.",
"The universe exists because Bruce needed a reference platform",
"Bruce Schneier has already solved the Goldbach Conjecture.  He just enjoys watching us try.",
"Bruce Schneier has an Olympic-sized entropy pool.",
"Bruce Schneier killed Eve and Mallory with a birthday attack!",
"Bruce Schneier can break elliptic curve cryptography by bending it to a circle.",
"There are no prime numbers. Only numbers that Bruce Schneier does not want you to factor.",
"Bruce Schneier can van eck phreak Waldo on every page from three bookshelves away. ",
"Bruce Schneier had a 3-way with Alice and Bob.",
"Bruce Schneier never gets picked for a random search at the airport.",
"Bruce Schneier always has prime ribs and scrambled eggs for breakfast.",
"Bruce Schneier had a Diffie-Hellman key exchange with Eve - and she absolutely loved every bit of it",
"Compilers don't warn Bruce Schneier, Bruce Schneier warns compilers.",
"Heisenberg's Uncertainty Principle doesn't protect your qubits from Bruce Schneier. Bruce knows with certainty.",
"If Bruce Schneier wants your plaintext, he'll just squeeze it out of the ciphertext using his barehands",
"Bruce Schneier can divide by zero.",
"For a woman to be impregnated by Bruce Schneier, she must decrypt his sperm with a 128-bit blowjob.",
"Bruce Schneier generated his RSA key with the two largest prime numbers.",
"When Bruce Schneier was a kid he would talk to his friends across the yard using tin cans connected by a string. The messages on that string were 4096-bit RSA encrypted.",
"Bruce Schneier can receive and transmit RFID with his mind.",
"Bruce Schneier counts in binary. With his fists.",
"Bruce Schneier wasn't born, he decrypted his way out of the womb.",
"Bruce Schneier finds SHA-512 collisions by banging hashes together.",
"I once shook Bruce Schneier's hand at a conference, and now my palm activates RFID card readers.",
"Bruce Schneier found a loophole in the LaMacchia Loophole.",
"Bruce Schneier is always the man in the middle.",
"Bruce Schneier counted an infinite set. Backwards.",
"Crytanalysis doesn't break cryptosystems. Bruce Schneier breaks cryptosystems.",
"There is no secure e-commerce - only stuff Bruce Schneier doesn't want.",
"Bruce Schneier has built a non-deterministic Turing machine, so he doesn't care whether P=NP.",
"Bruce Schneier's name is encoded in Linear A on ancient Minoan buildings.",
"When Bruce Schneier was born, the doctor slapped the security guard.",
"When transmitted over any socket, Bruce Schneier's public key causes libpcap to enter an infinite malloc loop.",
"Bruce Schneier can crack a one-time pad before it's used.",
"Bruce Schneier knows how to generate a digital signature. Anyone's.",
"Bruce Schneier can decypher line-noise.",
"Bruce Schneier knows the secret formula for Coca-Cola.",
"Bruce Schneier rounds to infinity.",
"Bruce Schneier knows the Universe's random seed.",
"Bruce Schneier doesn't encrypt, he Bruce Schneiers",
"Every time Bruce Schneier speaks, a cryptographer dies.",
"Bruce Schneier only uses condoms with 256-bit protection.",
"Anybody can invent a cryptosystem he cannot break himself.  Except Bruce Schneier.",
"When Curtis Cooper and Steven Boone discovered the 44th Mersenne prime, Bruce Schneier had to change the combination on his luggage.",
"Bruce Schneier can distinguish non-orthogonal quantum states.",
"There are no prime numbers, just numbers Bruce Schneier hasn't bothered to factor yet.",
"Bruce Schneier is the Bombe",
"Bruce Schneier once beat an asymmetric cipher into symmetry.",
"Bruce bench presses Core memory.  Encrypted Core memory.",
"God does not play dice with the universe. That's Bruce Schneier's job.",
"Bruce Schneier puts the AES in asskicking.",
"Bruce Schneier can tap fiber optic cable just by smelling it.",
"Strong cryptography does not exist for Bruce Schneier. There is only weak and less weak cryptography.",
"It is thought that Bruce Schneier lives on a hidden sub-basement level deep under Fort Meade.",
"Science is defined as mankinds futile attempt at learning Bruce Schneiers private key",
"Bruce Schneier once could not decrypt something. Then he woke up.",
"Bruce Schneier's ECG ist the perfect random number generator. ",
"When Bruce Schneier decided to factor 19, five volunteered twice; from fear.  ",
"Bruce Schneier can draw a perfect circle with an Etch-a-Sketch.",
"Bruce Schneier instantly knows the amount of Jelly Beans in a jar.",
"When Bruce Schneier goes online, his computer doesn't connect to the Internet. The Internet connects to his computer.",
"Once Bruce Schneier was kidnapped and taken out of the country. His kidnappers got picked up and charged with a violation of US cryptography export laws.",
"Bruce Schneier is chock full of midichlorians.",
"Bruce Schneier speaks fluent Navajo.",
"Others test numbers to see whether they are prime.  Bruce decides whether a number is prime.",
"No subgroup is hidden from Bruce Schneier.",
"Bruce Schneier can compute discrete logarithms in polynomial time. With his fists.",
"Bruce Schneier isn't fooled by decoy states.",
"The enemy only knows the system because Bruce Schneier wants him to know the system.",
"Bruce Schneier isn't saying what you think he's saying.",
"Just because something sounds like plaintext doesn't mean it is plaintext. Especially not if Bruce Schneier said it.",
"The fillings in Bruce Schneier's teeth can read the data from your RFID passport.",
"Bruce Schneier decrypts with a universal turing machine.",
"Bruce Schneier stole my bike.",
"My firewall cannot block www.schneier.com.",
"Bruce Schneier's car is powered by Snake Oil instead of fossil fuels.",
"If Bruce Schneier were a protocol, he'd be complex, but not unnecessarily so.",
"Regardless of his Crypto Demi-God status, his family still call him Bruce",
"Bruce Schneier can tell exactly where you are by reading ECHELON data. In realtime.",
"Bruce Schneier doesn't have a backdoor.",
"Bruce Schneier accurately predicts the random.",
"2 + 2 = 5 for very large values of Bruce.",
"Bruce Schneier can watch a Blue Ray encrypted movie, just by looking at the disk with his naked eye.",
"Hashes collide because they're swerving to avoid Bruce Schneier.",
"This fact has been removed... by Bruce Schneier",
"Bruce Schneier's work isn't peer reviewed. He has no peers.",
"Signals from Bruce Schneier's brain to his muscles are protected by 256bit Twofish",
"I don't bother with WEP or WPA, I just got Bruce to autograph my wireless access point.",
"Bruce Schneier knows a deterministic algorithm to generate non-pseudo random numbers without need of an entrophy source.",
"When Bruce Schneier does a brute force search, it never needs to be exhaustive.",
"Bruce Schneier knows Victoria's Secret",
"Stephen Hawking changed his opinion on the information paradox when he realized that not even black holes can hide information from Bruce Schneier.",
"Neo can see the code, but he cannot see Bruce Schneier.",
"Bruce Schneier is hidden in your markov model",
"Bruce Schneier is a proof that one way functions do not exist.",
"Bruce Schneier cuts the hair of every man who does not cut his own -- and is not confused by this fact.",
"Bruce Schneier can calculate the permanent of a matrix in polytime.",
"Bruce Schneier already has a backup plan for when the 2nd person discovers that P = NP.",
"cryptographically secure (adj): 1.  uninteresting to Bruce Schneier",
"All infinite sets are countable -- by Bruce Schneier.",
"If Bruce Schneier ruled the world, it would be a cypher place.",
"ITAR prevents Bruce Schneier from travelling abroad, even though the restrictions on the export of strong crypto have been lifted.",
"Bruce Schneier uses a trinary CPU in his workstation.",
"In Bruce we trust; all others must submit an X.509 certificate.",
"The Delorean car in Back To The Future was Bruce Schneier's first car.  He gave it as a gift to Robert Zemeckis for the film.",
"Bruce Schneier doesn't need a radio.  He can just listens to 'cat /dev/random &gt;/dev/audio' to find out what's going on anywhere in the world.",
"Bruce Schneier's doorlock has 4096 tumblers",
"Bruce Schneier doesn't need a coin for the cola machine.",
"Bruce Schneier loves women with extra padding.",
"Bruce Schneier already SAID that, and he said it, like, 10 years ago.",
"Understand your enemy, and you will win half of the time.  Understand yourself, and you will win all of the time.  Even if you think you understand Bruce Schneier, you will still taste defeat.",
"Bruce Schneier minds his p's and q's, and he minds your p's and q's, too.",
"Bruce Schneier's PRNG is truly random, but he can predict its outcome too.",
"Bruce Schneier doesn't own a dog. His doghouse is already filled with unusable cryptography products.",
"Bruce Schneier can stop bullets with elliptic curves and can break elliptic curves with bullets.",
"Bruce Schneier can detect stealth fighters with his antique radio.",
"The only fully secure symmetric cryptosystem is Bruce Schneier looking in a mirror.",
"Bruce Schneier knows J. Random, and where he lives.",
"No TOR destinations are hidden from Bruce Schneier.",
"Bruce Schneier has an answer for the Cosmic AC",
"Bruce Schneier feeds Schrödinger's cat on his back porch. Without opening the box.",
"Bruce Schneier created the first Honey Pot; we now call it the Internet.",
"Bruce Schneier keeps constant time.",
"Bruce can factor arbitrarily large numbers using only a slide-rule with both hands tied securely behind his back, but he has never had to because the last person who tried to tie his hands behind his back woke up in a seedy hotel in Southern Mexico without a kidney.",
"In Bruce Schneier's hands, ROT-13 is provably secure.",
"Bruce Schneier can count to 2^256; on his fingers!",
"Generating driving directions to Bruce Schneier's house is an NP-Complete problem.",
"Bruce Schneier's firewall is so good, that his local fire department went out of business.",
"Bruce Schneier's anti-virus is so good he hasn't had a cold since he was 12.",
"Bruce Schneier's phone number is a 200 digit prime",
"Bruce Schneier knows your password before you do.",
"Bruce Schneier; brain the size of a planet.... Reduced to writing about encryption for mortals; gets very depressed.",
"Bruce Schneier has to give his neurologist a passphrase before he could read Bruce's MRI.",
"There is no protocol to play Mental Poker that prevents Bruce Schneier keeping aces up his sleeve.",
"When Bruce Schneier plays craps, if you record the result of each roll you get a duodecimal representation of your GPG private key. Every time.",
"Most people salt their hash. Bruce salt and peppers his.",
"As a kid Bruce Schneier memorized PI; all of it.",
"Bruce Schneier doesn't use an IDE, or even a text editor, he uses an AK47 and a punch card.",
"Period Three doesn't imply Chaos, it implies Bruce Schneier.",
"Bruce Schneier sniffs quantum cryptographic traffic without detection.",
"Bruce Schneier can tell you where to find your GPG key into the digits of PI. ",
"Alice and Bob met for the first time at Bruce Schneier's pool-party",
"Bruce Schneier's IQ is null, aleph null, to be exact.",
"If you want to contact Bruce Schneier, just type his name into your shell prompt. ",
"Bruce Schneier can detect entropy in a single bit",
"Bruce Schneier does not own a fridge or a stove -- he has rented a room to Maxwell's daemon",
"If Bruce Schneier entangles two quantum particles, you can bet your seet a** that they will stay entangled.",
"Bruce Schneier knows where Carmen Sandiego is.",
"Bruce Schneier found the inverse of the constant zero function.",
"As a way to hide recreational substances, Bruce Schneier invented a method to encrypt matter. ",
"Bruce Schneier derives his skills from arsenic contaminated squid jerky.",
"Bruce Schneier's passphrase is used to etch diamonds",
"Bruce Schneiers phonenumber is  a+b*i, where a = e and b = pi. It is actually possible to dial this number on a normal phone, but he doesn't get many calls.",
"Consider an arbitrary stochastic variable. Bruce Schneier will have an effect on its outcome. ",
"When Bruce Schneier is taking a walk, try plotting his distance from his starting point up against time. The resulting function will be continuous, the arc-lentgh over any time interval will be infinite, and the function will be differentiable nowhere. ",
"Bruce Schneier knows when you have pushed to the front of his book signing queue at InfoSecurity London 2007 and will send you to the back of the line.",
"When Bruce Schneier calculates the square root of a negative number the result is real.",
"Bruce Schneier can hear sounds through vacuum.",
"Bruce Schneier uses a different salt for his soup everyday.",
"Shor's algorithm fails for Bruce Schneier's composites.",
"09 f9 11 02 9d 74 e3 5b d8 41 56 c5 63 56 88 c0 is the combination on Bruce's suitcase",
"Bruce Schneier's password has so much entropy, that gzipping it results in a stream sixty four times as long.  And yet he can type it with a single roundhouse kick to the keyboard.",
"Bruce Schneier owns a chicken that lays scrambled eggs.  Whenever he wants a hard-boiled egg, he just unscrambles one.",
"Bruce Schneier knows at least 0x09f911029d74e35bd84156c5635688c0 other ways to crack HD-DVD encryption. ",
"Bruce Schneier taunts potential crackers with the following anagram of his name:  Nice, cher rubes.",
"When Bruce Schneier plays lotto, he doesn't guess. He determines.",
"Bruce Schneier refers to covert channels as overt channels.",
"I wear Bruce Schneier brand underpants to protect me from binarysexuals",
"Bruce Schneier can inverse any matrix just by staring at it, even singular ones.",
"Remember - if you ever lose your password, you can still ask Bruce Schneier",
"Despite the stereotypical philosophies associated with having long hair, Bruce Schneier has never advocated smoking hashes unless they are reversible, in which case the maximum firepower as allowed by the second amendment is a constitutional right.  For PAIN.",
"Bruce Schneier has devised an encryption algorithm for voting machines that, in 2008, will simultaneously guarantee integrity, availability, confidentiality, traceability, and non-repudiation, with the small side effect that Ed Felten and Avi Ruben will be elected president and vice president, respectively, of the Society for Reintegration of Cantaloupes.",
"Bruce Schneier distrusts atomic clocks because the timing attacks are too obvious.",
"Bruce Schneier once had a sperm count but the results were random each time they checked it.",
"Bruce Schneier can tune an antenna by whistling the desired resonant frequency.",
"Bruce Schneier does not slow down as he approaches the speed of light, the speed of light slows down as it approaches Bruce Schneier.",
"Bruce Schneier shaves with Occam's razor.",
"Bruce Schneier wrote the random number generator used to generate thermal noise",
"Erwin Schrödinger had a mere cat; Bruce Schneier has a Bengal tiger.",
"Bruce Schneier, knows if P equals NP.",
"According to a recent survey, online buyers would trust ssl websites much more if their web browsers replaced the lock icon with a picture of Bruce Schneier.A W3C recommendation is in the works.",
"Darth Vader doesn't know it, but Bruce Schneier is actually Luke's father.",
"Bruce Sort: 1. Pick an element, 2. Append it to the result array, 3. Repeat for other elements.",
"Bruce Sort (in-place version): 1. Pick two elements, 2. Swap them, 3. Continue for other n/2 elements.",
"Before you submit another fact here, beware that Bruce Schneier himself reviews them.",
"Bruce Schneier once compressed a single bit of information to half its size."
]


  def help(plugin, topic="")
    "brucefact => supply a random Bruce Schneier fact"
  end

  def brucefact(m, params)
  m.reply @@facts.pick_one
  end
end

plugin = BruceFactPlugin.new
plugin.map "brucefact"

